name: IT

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  TEST_DIRNAME: ./itest_fsring.d

jobs:

  fstest:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -race -coverprofile=coverage.txt -covermode=atomic ./...
      env:
        ITEST_FSRING_DIR: ${{ env.TEST_DIRNAME }}
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
